---

- name: Install Apashe web server
  become: true
  ansible.builtin.package:
    name: httpd
    state: present

- name: Ensure Apache has selected state and enabled on boot.
  become: true  
  ansible.builtin.service:
    name: "httpd"
    state: "started"
    enabled: true

...