---

name: Start GitHub-Pages Deployment

on:
  workflow_run:
    workflows: 
      - "getting-started-ci"
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: 
          fetch-depth: 0
          submodules: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Convert code blocks
        run: |
          python markdown_parse.py

      - name: Start deployment process
        run: |
          mkdocs gh-deploy --config-file mkdocs.yml --remote-branch gh-pages --message "[Automated] deploy pages" --force
        working-directory:  ./blog

...
