---

name: getting-started-ci

on:
  push: 
    branches: ["main"]
    paths-ignore:
        - 'README.md'
        - '**/*.md'
        - .gitignore
        - ./meta/main.yml

permissions:
  contents: read

jobs:
  molecule-setup-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get install python3.10-venv

      - name: Create environment
        run: |
          python3.10 -m venv ~/.venv/ansible_env
          source ~/.venv/ansible_env/bin/activate

      - name: Write requirements
        run: |
          cat <<EOF > requirements.txt
          ansible==10.6.0
          molecule==24.9.0
          molecule-plugins[vagrant]
          docker==7.1.0
          EOF

      - name: Install requirements
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install -r requirements.txt


      - name: Install Virtualbox 7.1.4
        run: |
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
          sudo apt-get update
          sudo apt-get install -y linux-headers-$(uname -r) dkms
          sudo apt-get install virtualbox-7.1 -y

      - name: Verify VirtualBox installation
        run: VBoxManage --version

      - name: Install vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install vagrant -y

      - name: Verify Vagrant installation
        run: vagrant --version

      - name: Setup role and molecule scenario
        run: |
          ansible-galaxy role init example
          cd example
          molecule init scenario

      - name: Create default instance
        run: |
          molecule create

      - name: Verify default instance
        run: |
          molecule list

...
