---

name: getting-started-ci

on:
  push: 
    branches: ["main"]
    paths-ignore:
        - 'README.md'
        - '**/*.md'
        - .gitignore
        - ./meta/main.yml

permissions:
  contents: read

jobs:
  molecule-setup-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get install python3.10-venv

      - name: Create environment
        run: |
          python3.10 -m venv ~/.venv/ansible_env
          source ~/.venv/ansible_env/bin/activate

      - name: Get requirements
        run: |
          curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/ansible_molecule/getting_started/requirements.txt

      - name: Install requirements
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install -r requirements.txt

      - name: Install Virtualbox 7.1.4
        run: |
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor
          sudo apt-get update
          sudo apt-get install virtualbox-7.1 -y

      - name: Verify VirtualBox installation
        run: VBoxManage --version

      - name: Install vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install vagrant -y

      - name: Verify Vagrant installation
        run: vagrant --version

      - name: Setup role and molecule scenario
        run: |
          ansible-galaxy role init example
          cd example
          molecule init scenario

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Add role-name
        run: |
          cd example
          yq e '.galaxy_info.role_name = "example"' -i meta/main.yml
          yq e '.galaxy_info.namespace = "example_namespace"' -i meta/main.yml

      - name: Create default instance
        run: |
          cd example
          molecule create

      - name: Verify default instance
        run: |
          cd example
          molecule list

      - name: Destroy test instance
        run: |
          cd example
          molecule destroy

      - name: Reset scenario
        run: |
          cd example
          molecule reset

...
